[build]
builder = "NIXPACKS"
buildCommand = "cd server && go build -o myApp"
nixpacksPlan = {"providers":["...","go"]}
watchPatterns = ["/server"]

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10