// Code generated by MockGen. DO NOT EDIT.
// Source: ./services/timelineService.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sean-david-welch/farmec-v2/server/types"
)

// MockTimelineService is a mock of TimelineService interface.
type MockTimelineService struct {
	ctrl     *gomock.Controller
	recorder *MockTimelineServiceMockRecorder
}

// MockTimelineServiceMockRecorder is the mock recorder for MockTimelineService.
type MockTimelineServiceMockRecorder struct {
	mock *MockTimelineService
}

// NewMockTimelineService creates a new mock instance.
func NewMockTimelineService(ctrl *gomock.Controller) *MockTimelineService {
	mock := &MockTimelineService{ctrl: ctrl}
	mock.recorder = &MockTimelineServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimelineService) EXPECT() *MockTimelineServiceMockRecorder {
	return m.recorder
}

// CreateTimeline mocks base method.
func (m *MockTimelineService) CreateTimeline(timeline *types.Timeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTimeline", timeline)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTimeline indicates an expected call of CreateTimeline.
func (mr *MockTimelineServiceMockRecorder) CreateTimeline(timeline interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTimeline", reflect.TypeOf((*MockTimelineService)(nil).CreateTimeline), timeline)
}

// DeleteTimeline mocks base method.
func (m *MockTimelineService) DeleteTimeline(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTimeline", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTimeline indicates an expected call of DeleteTimeline.
func (mr *MockTimelineServiceMockRecorder) DeleteTimeline(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTimeline", reflect.TypeOf((*MockTimelineService)(nil).DeleteTimeline), id)
}

// GetTimelines mocks base method.
func (m *MockTimelineService) GetTimelines() ([]types.Timeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimelines")
	ret0, _ := ret[0].([]types.Timeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimelines indicates an expected call of GetTimelines.
func (mr *MockTimelineServiceMockRecorder) GetTimelines() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimelines", reflect.TypeOf((*MockTimelineService)(nil).GetTimelines))
}

// UpdateTimeline mocks base method.
func (m *MockTimelineService) UpdateTimeline(id string, timeline *types.Timeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTimeline", id, timeline)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTimeline indicates an expected call of UpdateTimeline.
func (mr *MockTimelineServiceMockRecorder) UpdateTimeline(id, timeline interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTimeline", reflect.TypeOf((*MockTimelineService)(nil).UpdateTimeline), id, timeline)
}
