// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/registrationRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sean-david-welch/farmec-v2/server/types"
)

// MockRegistrationRepository is a mock of RegistrationRepository interface.
type MockRegistrationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationRepositoryMockRecorder
}

// MockRegistrationRepositoryMockRecorder is the mock recorder for MockRegistrationRepository.
type MockRegistrationRepositoryMockRecorder struct {
	mock *MockRegistrationRepository
}

// NewMockRegistrationRepository creates a new mock instance.
func NewMockRegistrationRepository(ctrl *gomock.Controller) *MockRegistrationRepository {
	mock := &MockRegistrationRepository{ctrl: ctrl}
	mock.recorder = &MockRegistrationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationRepository) EXPECT() *MockRegistrationRepositoryMockRecorder {
	return m.recorder
}

// CreateRegistration mocks base method.
func (m *MockRegistrationRepository) CreateRegistration(registration *types.MachineRegistration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRegistration", registration)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRegistration indicates an expected call of CreateRegistration.
func (mr *MockRegistrationRepositoryMockRecorder) CreateRegistration(registration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRegistration", reflect.TypeOf((*MockRegistrationRepository)(nil).CreateRegistration), registration)
}

// DeleteRegistration mocks base method.
func (m *MockRegistrationRepository) DeleteRegistration(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRegistration", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRegistration indicates an expected call of DeleteRegistration.
func (mr *MockRegistrationRepositoryMockRecorder) DeleteRegistration(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRegistration", reflect.TypeOf((*MockRegistrationRepository)(nil).DeleteRegistration), id)
}

// GetRegistrationById mocks base method.
func (m *MockRegistrationRepository) GetRegistrationById(id string) (*types.MachineRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationById", id)
	ret0, _ := ret[0].(*types.MachineRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationById indicates an expected call of GetRegistrationById.
func (mr *MockRegistrationRepositoryMockRecorder) GetRegistrationById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationById", reflect.TypeOf((*MockRegistrationRepository)(nil).GetRegistrationById), id)
}

// GetRegistrations mocks base method.
func (m *MockRegistrationRepository) GetRegistrations() ([]types.MachineRegistration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrations")
	ret0, _ := ret[0].([]types.MachineRegistration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrations indicates an expected call of GetRegistrations.
func (mr *MockRegistrationRepositoryMockRecorder) GetRegistrations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrations", reflect.TypeOf((*MockRegistrationRepository)(nil).GetRegistrations))
}

// UpdateRegistration mocks base method.
func (m *MockRegistrationRepository) UpdateRegistration(id string, registration *types.MachineRegistration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRegistration", id, registration)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRegistration indicates an expected call of UpdateRegistration.
func (mr *MockRegistrationRepositoryMockRecorder) UpdateRegistration(id, registration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRegistration", reflect.TypeOf((*MockRegistrationRepository)(nil).UpdateRegistration), id, registration)
}
