// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/privacyRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sean-david-welch/farmec-v2/server/types"
)

// MockPrivacyRepository is a mock of PrivacyRepository interface.
type MockPrivacyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPrivacyRepositoryMockRecorder
}

// MockPrivacyRepositoryMockRecorder is the mock recorder for MockPrivacyRepository.
type MockPrivacyRepositoryMockRecorder struct {
	mock *MockPrivacyRepository
}

// NewMockPrivacyRepository creates a new mock instance.
func NewMockPrivacyRepository(ctrl *gomock.Controller) *MockPrivacyRepository {
	mock := &MockPrivacyRepository{ctrl: ctrl}
	mock.recorder = &MockPrivacyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrivacyRepository) EXPECT() *MockPrivacyRepositoryMockRecorder {
	return m.recorder
}

// CreatePrivacy mocks base method.
func (m *MockPrivacyRepository) CreatePrivacy(privacy *types.Privacy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivacy", privacy)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePrivacy indicates an expected call of CreatePrivacy.
func (mr *MockPrivacyRepositoryMockRecorder) CreatePrivacy(privacy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivacy", reflect.TypeOf((*MockPrivacyRepository)(nil).CreatePrivacy), privacy)
}

// DeletePrivacy mocks base method.
func (m *MockPrivacyRepository) DeletePrivacy(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrivacy", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrivacy indicates an expected call of DeletePrivacy.
func (mr *MockPrivacyRepositoryMockRecorder) DeletePrivacy(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrivacy", reflect.TypeOf((*MockPrivacyRepository)(nil).DeletePrivacy), id)
}

// GetPrivacy mocks base method.
func (m *MockPrivacyRepository) GetPrivacy() ([]types.Privacy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivacy")
	ret0, _ := ret[0].([]types.Privacy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivacy indicates an expected call of GetPrivacy.
func (mr *MockPrivacyRepositoryMockRecorder) GetPrivacy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivacy", reflect.TypeOf((*MockPrivacyRepository)(nil).GetPrivacy))
}

// UpdatePrivacy mocks base method.
func (m *MockPrivacyRepository) UpdatePrivacy(id string, privacy *types.Privacy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrivacy", id, privacy)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePrivacy indicates an expected call of UpdatePrivacy.
func (mr *MockPrivacyRepositoryMockRecorder) UpdatePrivacy(id, privacy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePrivacy", reflect.TypeOf((*MockPrivacyRepository)(nil).UpdatePrivacy), id, privacy)
}
