// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository/termsRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sean-david-welch/farmec-v2/server/types"
)

// MockTermsRepository is a mock of TermsRepository interface.
type MockTermsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTermsRepositoryMockRecorder
}

// MockTermsRepositoryMockRecorder is the mock recorder for MockTermsRepository.
type MockTermsRepositoryMockRecorder struct {
	mock *MockTermsRepository
}

// NewMockTermsRepository creates a new mock instance.
func NewMockTermsRepository(ctrl *gomock.Controller) *MockTermsRepository {
	mock := &MockTermsRepository{ctrl: ctrl}
	mock.recorder = &MockTermsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTermsRepository) EXPECT() *MockTermsRepositoryMockRecorder {
	return m.recorder
}

// CreateTerm mocks base method.
func (m *MockTermsRepository) CreateTerm(term *types.Terms) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTerm", term)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTerm indicates an expected call of CreateTerm.
func (mr *MockTermsRepositoryMockRecorder) CreateTerm(term interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTerm", reflect.TypeOf((*MockTermsRepository)(nil).CreateTerm), term)
}

// DeleteTerm mocks base method.
func (m *MockTermsRepository) DeleteTerm(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTerm", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTerm indicates an expected call of DeleteTerm.
func (mr *MockTermsRepositoryMockRecorder) DeleteTerm(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTerm", reflect.TypeOf((*MockTermsRepository)(nil).DeleteTerm), id)
}

// GetTerms mocks base method.
func (m *MockTermsRepository) GetTerms() ([]types.Terms, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTerms")
	ret0, _ := ret[0].([]types.Terms)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTerms indicates an expected call of GetTerms.
func (mr *MockTermsRepositoryMockRecorder) GetTerms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTerms", reflect.TypeOf((*MockTermsRepository)(nil).GetTerms))
}

// UpdateTerm mocks base method.
func (m *MockTermsRepository) UpdateTerm(id string, term *types.Terms) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTerm", id, term)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTerm indicates an expected call of UpdateTerm.
func (mr *MockTermsRepositoryMockRecorder) UpdateTerm(id, term interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTerm", reflect.TypeOf((*MockTermsRepository)(nil).UpdateTerm), id, term)
}
