// Code generated by MockGen. DO NOT EDIT.
// Source: ./services/warrantyService.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sean-david-welch/farmec-v2/server/types"
)

// MockWarrantyService is a mock of WarrantyService interface.
type MockWarrantyService struct {
	ctrl     *gomock.Controller
	recorder *MockWarrantyServiceMockRecorder
}

// MockWarrantyServiceMockRecorder is the mock recorder for MockWarrantyService.
type MockWarrantyServiceMockRecorder struct {
	mock *MockWarrantyService
}

// NewMockWarrantyService creates a new mock instance.
func NewMockWarrantyService(ctrl *gomock.Controller) *MockWarrantyService {
	mock := &MockWarrantyService{ctrl: ctrl}
	mock.recorder = &MockWarrantyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarrantyService) EXPECT() *MockWarrantyServiceMockRecorder {
	return m.recorder
}

// CreateWarranty mocks base method.
func (m *MockWarrantyService) CreateWarranty(warranty *types.WarrantyClaim, parts []types.PartsRequired) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWarranty", warranty, parts)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWarranty indicates an expected call of CreateWarranty.
func (mr *MockWarrantyServiceMockRecorder) CreateWarranty(warranty, parts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWarranty", reflect.TypeOf((*MockWarrantyService)(nil).CreateWarranty), warranty, parts)
}

// DeleteWarranty mocks base method.
func (m *MockWarrantyService) DeleteWarranty(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWarranty", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWarranty indicates an expected call of DeleteWarranty.
func (mr *MockWarrantyServiceMockRecorder) DeleteWarranty(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWarranty", reflect.TypeOf((*MockWarrantyService)(nil).DeleteWarranty), id)
}

// GetWarranties mocks base method.
func (m *MockWarrantyService) GetWarranties() ([]types.DealerOwnerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWarranties")
	ret0, _ := ret[0].([]types.DealerOwnerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWarranties indicates an expected call of GetWarranties.
func (mr *MockWarrantyServiceMockRecorder) GetWarranties() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarranties", reflect.TypeOf((*MockWarrantyService)(nil).GetWarranties))
}

// GetWarrantyById mocks base method.
func (m *MockWarrantyService) GetWarrantyById(id string) (*types.WarrantyClaim, []types.PartsRequired, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWarrantyById", id)
	ret0, _ := ret[0].(*types.WarrantyClaim)
	ret1, _ := ret[1].([]types.PartsRequired)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetWarrantyById indicates an expected call of GetWarrantyById.
func (mr *MockWarrantyServiceMockRecorder) GetWarrantyById(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarrantyById", reflect.TypeOf((*MockWarrantyService)(nil).GetWarrantyById), id)
}

// UpdateWarranty mocks base method.
func (m *MockWarrantyService) UpdateWarranty(id string, warranty *types.WarrantyClaim, parts []types.PartsRequired) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWarranty", id, warranty, parts)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWarranty indicates an expected call of UpdateWarranty.
func (mr *MockWarrantyServiceMockRecorder) UpdateWarranty(id, warranty, parts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWarranty", reflect.TypeOf((*MockWarrantyService)(nil).UpdateWarranty), id, warranty, parts)
}
