// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Blog struct {
	ID         string
	Title      string
	Date       sql.NullString
	MainImage  sql.NullString
	Subheading sql.NullString
	Body       sql.NullString
	Created    sql.NullString
}

type Carousel struct {
	ID      string
	Name    string
	Image   sql.NullString
	Created sql.NullString
}

type Employee struct {
	ID           string
	Name         string
	Email        string
	Role         string
	ProfileImage sql.NullString
	Created      sql.NullString
}

type Exhibition struct {
	ID       string
	Title    string
	Date     sql.NullString
	Location sql.NullString
	Info     sql.NullString
	Created  sql.NullString
}

type LineItem struct {
	ID    string
	Name  string
	Price float64
	Image sql.NullString
}

type Machine struct {
	ID           string
	SupplierID   string
	Name         string
	MachineImage sql.NullString
	Description  sql.NullString
	MachineLink  sql.NullString
	Created      sql.NullString
}

type MachineRegistration struct {
	ID               string
	DealerName       string
	DealerAddress    sql.NullString
	OwnerName        string
	OwnerAddress     sql.NullString
	MachineModel     string
	SerialNumber     string
	InstallDate      sql.NullString
	InvoiceNumber    sql.NullString
	CompleteSupply   sql.NullInt64
	PdiComplete      sql.NullInt64
	PtoCorrect       sql.NullInt64
	MachineTestRun   sql.NullInt64
	SafetyInduction  sql.NullInt64
	OperatorHandbook sql.NullInt64
	Date             sql.NullString
	CompletedBy      sql.NullString
	Created          sql.NullString
}

type PartsRequired struct {
	ID             string
	WarrantyID     string
	PartNumber     sql.NullString
	QuantityNeeded string
	InvoiceNumber  sql.NullString
	Description    sql.NullString
}

type Privacy struct {
	ID      string
	Title   string
	Body    sql.NullString
	Created sql.NullString
}

type Product struct {
	ID           string
	MachineID    string
	Name         string
	ProductImage sql.NullString
	Description  sql.NullString
	ProductLink  sql.NullString
}

type SparePart struct {
	ID             string
	SupplierID     string
	Name           string
	PartsImage     sql.NullString
	SparePartsLink sql.NullString
}

type Supplier struct {
	ID              string
	Name            string
	LogoImage       sql.NullString
	MarketingImage  sql.NullString
	Description     sql.NullString
	SocialFacebook  sql.NullString
	SocialTwitter   sql.NullString
	SocialInstagram sql.NullString
	SocialYoutube   sql.NullString
	SocialLinkedin  sql.NullString
	SocialWebsite   sql.NullString
	Created         sql.NullString
}

type Term struct {
	ID      string
	Title   string
	Body    sql.NullString
	Created sql.NullString
}

type Timeline struct {
	ID      string
	Title   string
	Date    sql.NullString
	Body    sql.NullString
	Created sql.NullString
}

type Video struct {
	ID           string
	SupplierID   string
	WebUrl       sql.NullString
	Title        sql.NullString
	Description  sql.NullString
	VideoID      sql.NullString
	ThumbnailUrl sql.NullString
	Created      sql.NullString
}

type WarrantyClaim struct {
	ID             string
	Dealer         string
	DealerContact  sql.NullString
	OwnerName      string
	MachineModel   string
	SerialNumber   string
	InstallDate    sql.NullString
	FailureDate    sql.NullString
	RepairDate     sql.NullString
	FailureDetails sql.NullString
	RepairDetails  sql.NullString
	LabourHours    sql.NullString
	CompletedBy    sql.NullString
	Created        sql.NullString
}
