# Generated by Django 6.0.2 on 2026-03-29 18:49

import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=255, verbose_name='title')),
                ('body', models.TextField(blank=True, help_text='Legal privacy policy text', null=True, verbose_name='body')),
            ],
            options={
                'verbose_name': 'privacy policy',
                'verbose_name_plural': 'privacy policy',
                'db_table': 'Privacy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=255, verbose_name='title')),
                ('body', models.TextField(blank=True, help_text='Legal terms and conditions text', null=True, verbose_name='body')),
            ],
            options={
                'verbose_name': 'terms & conditions',
                'verbose_name_plural': 'terms & conditions',
                'db_table': 'Terms',
                'managed': True,
            },
        ),
    ]
