# Generated by Django 6.0.1 on 2026-01-26 07:52

import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('legal', '0002_alter_privacy_options_alter_terms_options'), ('legal', '0003_privacy_modified_privacy_order_privacy_publish_and_more'), ('legal', '0004_alter_privacy_body_alter_privacy_created_and_more')]

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacy',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='privacy',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='privacy',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='terms',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='terms',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='terms',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='terms',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='body',
            field=models.TextField(blank=True, help_text='Legal privacy policy text', null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='title',
            field=models.CharField(help_text='Page title', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='body',
            field=models.TextField(blank=True, help_text='Legal terms and conditions text', null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='title',
            field=models.CharField(help_text='Page title', max_length=255, verbose_name='title'),
        ),
    ]
