# Generated by Django 6.0.1 on 2026-01-25 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_privacy_modified_privacy_order_privacy_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='body',
            field=models.TextField(blank=True, help_text='Legal privacy policy text', null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='title',
            field=models.CharField(help_text='Page title', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='body',
            field=models.TextField(blank=True, help_text='Legal terms and conditions text', null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='terms',
            name='title',
            field=models.CharField(help_text='Page title', max_length=255, verbose_name='title'),
        ),
    ]
