# Generated by Django 6.0.2 on 2026-03-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_alter_privacy_options_alter_terms_options_squashed_0004_alter_privacy_body_alter_privacy_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacy',
            options={'managed': True, 'verbose_name': 'privacy policy', 'verbose_name_plural': 'privacy policy'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'managed': True, 'verbose_name': 'terms & conditions', 'verbose_name_plural': 'terms & conditions'},
        ),
    ]
