# Generated by Django 6.0.2 on 2026-03-29 18:49

import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Employee full name', max_length=255, verbose_name='name')),
                ('email', models.EmailField(help_text='Work email address', max_length=254, verbose_name='email')),
                ('role', models.CharField(help_text='Job title or position', max_length=255, verbose_name='role')),
                ('profile_image', models.ImageField(blank=True, help_text='Employee profile photo', null=True, upload_to='farmec_images/Employees/', verbose_name='profile image')),
            ],
            options={
                'db_table': 'Employee',
                'managed': True,
            },
        ),
    ]
