# Generated by Django 6.0.1 on 2026-01-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('role', models.TextField()),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Employee',
                'managed': False,
            },
        ),
    ]
