# Generated by Django 6.0.1 on 2026-01-26 07:55

import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('team', '0002_alter_employee_options'), ('team', '0003_employee_modified_employee_order_employee_publish_and_more'), ('team', '0004_alter_employee_email_alter_employee_id_and_more')]

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='employee',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='employee',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='employee',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='employee',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text='Work email address', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Employee full name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.URLField(blank=True, help_text='URL to employee profile photo', null=True, verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(help_text='Job title or position', max_length=255, verbose_name='role'),
        ),
    ]
