# Generated by Django 6.0.1 on 2026-01-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True},
        ),
    ]
