# Generated by Django 6.0.1 on 2026-01-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_employee_modified_employee_order_employee_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(help_text='Work email address', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Employee full name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.URLField(blank=True, help_text='URL to employee profile photo', null=True, verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(help_text='Job title or position', max_length=255, verbose_name='role'),
        ),
    ]
