# Generated by Django 6.0.2 on 2026-03-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_employee_options_squashed_0004_alter_employee_email_alter_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Employee profile photo', null=True, upload_to='farmec_images/Employees/', verbose_name='profile image'),
        ),
    ]
