"""
Django settings for farmec project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os.path
from pathlib import Path

import environ
from django.urls import reverse_lazy

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s^+f^9tux8*a&&^%3evn@nfradmm)k16ea$q^=8wk12cfa_1=x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Model apps
    'theme',
    'catalog',
    'content',
    'support',
    'team',
    'legal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'farmec.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'theme' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'theme.context_processors.suppliers',
            ],
        },
    },
]

WSGI_APPLICATION = 'farmec.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'database', 'database.db'),
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


UNFOLD = {
    "SITE_TITLE": "Farmec Admin",
    "SITE_HEADER": "Farmec Administration",
    "SITE_SYMBOL": "agriculture",
    "COLORS": {
        "primary": {
            "50": "254 242 242",
            "100": "254 226 226",
            "200": "254 202 202",
            "300": "252 165 165",
            "400": "248 113 113",
            "500": "220 38 38",
            "600": "185 28 28",
            "700": "153 27 27",
            "800": "127 29 29",
            "900": "127 29 29",
            "950": "69 10 10",
        },
        "gray": {
            "50": "250 250 250",
            "100": "245 245 245",
            "200": "229 229 229",
            "300": "212 212 212",
            "400": "163 163 163",
            "500": "115 115 115",
            "600": "82 82 82",
            "700": "64 64 64",
            "800": "38 38 38",
            "900": "10 10 10",
            "950": "0 0 0",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Catalog",
                "separator": True,
                "items": [
                    {"title": "Suppliers", "icon": "factory", "link": reverse_lazy("admin:catalog_supplier_changelist")},
                    {"title": "Machines", "icon": "agriculture", "link": reverse_lazy("admin:catalog_machine_changelist")},
                    {"title": "Products", "icon": "inventory_2", "link": reverse_lazy("admin:catalog_product_changelist")},
                    {"title": "Spare Parts", "icon": "settings_suggest", "link": reverse_lazy("admin:catalog_spareparts_changelist")},
                    {"title": "Videos", "icon": "play_circle", "link": reverse_lazy("admin:catalog_video_changelist")},
                    {"title": "Line Items", "icon": "list_alt", "link": reverse_lazy("admin:catalog_lineitems_changelist")},
                ],
            },
            {
                "title": "Content",
                "separator": True,
                "items": [
                    {"title": "Blog Posts", "icon": "article", "link": reverse_lazy("admin:content_blog_changelist")},
                    {"title": "Carousel", "icon": "view_carousel", "link": reverse_lazy("admin:content_carousel_changelist")},
                    {"title": "Exhibitions", "icon": "event", "link": reverse_lazy("admin:content_exhibition_changelist")},
                    {"title": "Timeline", "icon": "timeline", "link": reverse_lazy("admin:content_timeline_changelist")},
                ],
            },
            {
                "title": "Team",
                "separator": True,
                "items": [
                    {"title": "Employees", "icon": "badge", "link": reverse_lazy("admin:team_employee_changelist")},
                ],
            },
            {
                "title": "Support",
                "separator": True,
                "items": [
                    {"title": "Warranty Claims", "icon": "gavel", "link": reverse_lazy("admin:support_warrantyclaim_changelist")},
                    {"title": "Parts Required", "icon": "build", "link": reverse_lazy("admin:support_partsrequired_changelist")},
                    {"title": "Machine Registrations", "icon": "app_registration", "link": reverse_lazy("admin:support_machineregistration_changelist")},
                ],
            },
            {
                "title": "Legal",
                "separator": True,
                "items": [
                    {"title": "Privacy Policy", "icon": "policy", "link": reverse_lazy("admin:legal_privacy_changelist")},
                    {"title": "Terms & Conditions", "icon": "description", "link": reverse_lazy("admin:legal_terms_changelist")},
                ],
            },
        ],
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Django Storages - AWS S3 Configuration
# https://django-storages.readthedocs.io/en/latest/backends/amazon-s3.html
STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}
# AWS S3 Configuration
AWS_STORAGE_BUCKET_NAME = 'farmec.ie'
AWS_S3_REGION_NAME = 'eu-west-1'
AWS_S3_ACCESS_KEY_ID = env('AWS_ACCESS_KEY', default='')
AWS_S3_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY', default='')
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_DEFAULT_ACL = 'public-read'
AWS_QUERYSTRING_AUTH = False
