# Generated by Django 6.0.1 on 2026-01-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machineregistration',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('dealer_name', models.TextField()),
                ('dealer_address', models.TextField(blank=True, null=True)),
                ('owner_name', models.TextField()),
                ('owner_address', models.TextField(blank=True, null=True)),
                ('machine_model', models.TextField()),
                ('serial_number', models.TextField()),
                ('install_date', models.TextField(blank=True, null=True)),
                ('invoice_number', models.TextField(blank=True, null=True)),
                ('complete_supply', models.IntegerField(blank=True, null=True)),
                ('pdi_complete', models.IntegerField(blank=True, null=True)),
                ('pto_correct', models.IntegerField(blank=True, null=True)),
                ('machine_test_run', models.IntegerField(blank=True, null=True)),
                ('safety_induction', models.IntegerField(blank=True, null=True)),
                ('operator_handbook', models.IntegerField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('completed_by', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MachineRegistration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partsrequired',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('warranty', models.TextField(blank=True, null=True)),
                ('part_number', models.TextField(blank=True, null=True)),
                ('quantity_needed', models.TextField()),
                ('invoice_number', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PartsRequired',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warrantyclaim',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('dealer', models.TextField()),
                ('dealer_contact', models.TextField(blank=True, null=True)),
                ('owner_name', models.TextField()),
                ('machine_model', models.TextField()),
                ('serial_number', models.TextField()),
                ('install_date', models.TextField(blank=True, null=True)),
                ('failure_date', models.TextField(blank=True, null=True)),
                ('repair_date', models.TextField(blank=True, null=True)),
                ('failure_details', models.TextField(blank=True, null=True)),
                ('repair_details', models.TextField(blank=True, null=True)),
                ('labour_hours', models.TextField(blank=True, null=True)),
                ('completed_by', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WarrantyClaim',
                'managed': False,
            },
        ),
    ]
