# Generated by Django 6.0.2 on 2026-03-29 18:49

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machineregistration',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(help_text='Authorized dealer business name', max_length=255, verbose_name='dealer name')),
                ('dealer_address', models.CharField(blank=True, help_text='Dealer location address', max_length=500, null=True, verbose_name='dealer address')),
                ('owner_name', models.CharField(help_text='Machine owner/customer name', max_length=255, verbose_name='owner name')),
                ('owner_address', models.CharField(blank=True, help_text='Owner location address', max_length=500, null=True, verbose_name='owner address')),
                ('machine_model', models.CharField(help_text='Model name/number of machine', max_length=255, verbose_name='machine model')),
                ('serial_number', models.CharField(db_index=True, help_text='Machine serial number', max_length=100, verbose_name='serial number')),
                ('install_date', models.DateField(blank=True, help_text='Date of installation', null=True, verbose_name='install date')),
                ('invoice_number', models.CharField(blank=True, help_text='Sales invoice reference', max_length=100, null=True, verbose_name='invoice number')),
                ('complete_supply', models.BooleanField(default=False, help_text='All items and documents included with delivery', verbose_name='complete supply')),
                ('pdi_complete', models.BooleanField(default=False, help_text='Pre-Delivery Inspection completed', verbose_name='PDI complete')),
                ('pto_correct', models.BooleanField(default=False, help_text='Power Take-Off correctly configured', verbose_name='PTO correct')),
                ('machine_test_run', models.BooleanField(default=False, help_text='Machine tested and working', verbose_name='machine test run')),
                ('safety_induction', models.BooleanField(default=False, help_text='Owner received safety training', verbose_name='safety induction')),
                ('operator_handbook', models.BooleanField(default=False, help_text='Owner manual provided', verbose_name='operator handbook')),
                ('date', models.DateField(blank=True, help_text='Registration completion date', null=True, verbose_name='date')),
                ('completed_by', models.CharField(blank=True, help_text='Person who completed registration', max_length=255, null=True, verbose_name='completed by')),
            ],
            options={
                'verbose_name': 'machine registration',
                'verbose_name_plural': 'machine registrations',
                'db_table': 'MachineRegistration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Warrantyclaim',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer', models.CharField(help_text='Authorized dealer name', max_length=255, verbose_name='dealer')),
                ('dealer_contact', models.CharField(blank=True, help_text='Dealer contact person or phone', max_length=255, null=True, verbose_name='dealer contact')),
                ('owner_name', models.CharField(help_text='Machine owner/customer name', max_length=255, verbose_name='owner name')),
                ('machine_model', models.CharField(help_text='Model name/number of the machine', max_length=255, verbose_name='machine model')),
                ('serial_number', models.CharField(db_index=True, help_text='Machine serial number for identification', max_length=100, verbose_name='serial number')),
                ('install_date', models.DateField(blank=True, help_text='Date machine was installed', null=True, verbose_name='install date')),
                ('failure_date', models.DateField(blank=True, help_text='Date failure occurred', null=True, verbose_name='failure date')),
                ('repair_date', models.DateField(blank=True, help_text='Date repair was completed', null=True, verbose_name='repair date')),
                ('failure_details', models.TextField(blank=True, help_text='Description of the failure/damage', null=True, verbose_name='failure details')),
                ('repair_details', models.TextField(blank=True, help_text='Description of work performed', null=True, verbose_name='repair details')),
                ('labour_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Hours of labour for repair', max_digits=8, null=True, verbose_name='labour hours')),
                ('completed_by', models.CharField(blank=True, help_text='Technician or person who completed repair', max_length=255, null=True, verbose_name='completed by')),
            ],
            options={
                'verbose_name': 'warranty claim',
                'verbose_name_plural': 'warranty claims',
                'db_table': 'WarrantyClaim',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Partsrequired',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, db_index=True, help_text='Supplier part number or SKU', max_length=100, null=True, verbose_name='part number')),
                ('quantity_needed', models.PositiveIntegerField(help_text='Number of units required', verbose_name='quantity needed')),
                ('invoice_number', models.CharField(blank=True, help_text='Supplier invoice reference', max_length=100, null=True, verbose_name='invoice number')),
                ('description', models.TextField(blank=True, help_text='Part name and specifications', null=True, verbose_name='description')),
                ('warranty', models.ForeignKey(blank=True, help_text='Warranty claim this part is required for', null=True, on_delete=django.db.models.deletion.CASCADE, to='support.warrantyclaim', verbose_name='warranty claim')),
            ],
            options={
                'verbose_name': 'part required',
                'verbose_name_plural': 'parts required',
                'db_table': 'PartsRequired',
                'managed': True,
            },
        ),
    ]
