# Generated by Django 6.0.1 on 2026-01-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineregistration',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='partsrequired',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='warrantyclaim',
            options={'managed': True},
        ),
    ]
