# Generated by Django 6.0.1 on 2026-01-25 21:52

import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_machineregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineregistration',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='machineregistration',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='machineregistration',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='machineregistration',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='partsrequired',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AddField(
            model_name='partsrequired',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='partsrequired',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='partsrequired',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='partsrequired',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='warrantyclaim',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
    ]
