# Generated by Django 6.0.4 on 2026-05-16 10:57

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_normalize_uuids'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyImage',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Repair or damage photo', upload_to='farmec_images/Warranty/', verbose_name='image')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='support.warrantyclaim', verbose_name='warranty claim')),
            ],
            options={
                'verbose_name': 'warranty image',
                'verbose_name_plural': 'warranty images',
                'db_table': 'WarrantyImage',
                'managed': True,
            },
        ),
    ]
