# Generated by Django 6.0.1 on 2026-01-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_machineregistration_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineregistration',
            name='complete_supply',
            field=models.BooleanField(default=False, help_text='All items and documents included with delivery', verbose_name='complete supply'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='completed_by',
            field=models.CharField(blank=True, help_text='Person who completed registration', max_length=255, null=True, verbose_name='completed by'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='date',
            field=models.DateField(blank=True, help_text='Registration completion date', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='dealer_address',
            field=models.CharField(blank=True, help_text='Dealer location address', max_length=500, null=True, verbose_name='dealer address'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='dealer_name',
            field=models.CharField(help_text='Authorized dealer business name', max_length=255, verbose_name='dealer name'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='install_date',
            field=models.DateField(blank=True, help_text='Date of installation', null=True, verbose_name='install date'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Sales invoice reference', max_length=100, null=True, verbose_name='invoice number'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='machine_model',
            field=models.CharField(help_text='Model name/number of machine', max_length=255, verbose_name='machine model'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='machine_test_run',
            field=models.BooleanField(default=False, help_text='Machine tested and working', verbose_name='machine test run'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='operator_handbook',
            field=models.BooleanField(default=False, help_text='Owner manual provided', verbose_name='operator handbook'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='owner_address',
            field=models.CharField(blank=True, help_text='Owner location address', max_length=500, null=True, verbose_name='owner address'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='owner_name',
            field=models.CharField(help_text='Machine owner/customer name', max_length=255, verbose_name='owner name'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='pdi_complete',
            field=models.BooleanField(default=False, help_text='Pre-Delivery Inspection completed', verbose_name='PDI complete'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='pto_correct',
            field=models.BooleanField(default=False, help_text='Power Take-Off correctly configured', verbose_name='PTO correct'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='safety_induction',
            field=models.BooleanField(default=False, help_text='Owner received safety training', verbose_name='safety induction'),
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='serial_number',
            field=models.CharField(db_index=True, help_text='Machine serial number', max_length=100, verbose_name='serial number'),
        ),
        migrations.AlterField(
            model_name='partsrequired',
            name='description',
            field=models.TextField(blank=True, help_text='Part name and specifications', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='partsrequired',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partsrequired',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Supplier invoice reference', max_length=100, null=True, verbose_name='invoice number'),
        ),
        migrations.AlterField(
            model_name='partsrequired',
            name='part_number',
            field=models.CharField(blank=True, db_index=True, help_text='Supplier part number or SKU', max_length=100, null=True, verbose_name='part number'),
        ),
        migrations.AlterField(
            model_name='partsrequired',
            name='quantity_needed',
            field=models.PositiveIntegerField(help_text='Number of units required', verbose_name='quantity needed'),
        ),
        migrations.AlterField(
            model_name='partsrequired',
            name='warranty',
            field=models.TextField(blank=True, help_text='Reference to Warrantyclaim ID', null=True, verbose_name='warranty'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='completed_by',
            field=models.CharField(blank=True, help_text='Technician or person who completed repair', max_length=255, null=True, verbose_name='completed by'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='dealer',
            field=models.CharField(help_text='Authorized dealer name', max_length=255, verbose_name='dealer'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='dealer_contact',
            field=models.CharField(blank=True, help_text='Dealer contact person or phone', max_length=255, null=True, verbose_name='dealer contact'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='failure_date',
            field=models.DateField(blank=True, help_text='Date failure occurred', null=True, verbose_name='failure date'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='failure_details',
            field=models.TextField(blank=True, help_text='Description of the failure/damage', null=True, verbose_name='failure details'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='install_date',
            field=models.DateField(blank=True, help_text='Date machine was installed', null=True, verbose_name='install date'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='labour_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours of labour for repair', max_digits=8, null=True, verbose_name='labour hours'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='machine_model',
            field=models.CharField(help_text='Model name/number of the machine', max_length=255, verbose_name='machine model'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='owner_name',
            field=models.CharField(help_text='Machine owner/customer name', max_length=255, verbose_name='owner name'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='repair_date',
            field=models.DateField(blank=True, help_text='Date repair was completed', null=True, verbose_name='repair date'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='repair_details',
            field=models.TextField(blank=True, help_text='Description of work performed', null=True, verbose_name='repair details'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='serial_number',
            field=models.CharField(db_index=True, help_text='Machine serial number for identification', max_length=100, verbose_name='serial number'),
        ),
    ]
