# Generated by Django 6.0.1 on 2026-01-25 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_machineregistration_complete_supply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsrequired',
            name='warranty',
            field=models.ForeignKey(blank=True, help_text='Warranty claim this part is required for', null=True, on_delete=django.db.models.deletion.CASCADE, to='support.warrantyclaim', verbose_name='warranty claim'),
        ),
    ]
