# Generated by Django 6.0.2 on 2026-03-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_machineregistration_options_and_more_squashed_0005_alter_partsrequired_warranty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machineregistration',
            options={'managed': True, 'verbose_name': 'machine registration', 'verbose_name_plural': 'machine registrations'},
        ),
        migrations.AlterModelOptions(
            name='partsrequired',
            options={'managed': True, 'verbose_name': 'part required', 'verbose_name_plural': 'parts required'},
        ),
        migrations.AlterModelOptions(
            name='warrantyclaim',
            options={'managed': True, 'verbose_name': 'warranty claim', 'verbose_name_plural': 'warranty claims'},
        ),
    ]
