root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
full_bin = "ENV=development PORT=8000 ./tmp/main"
include_ext = ["go", "templ", "html", "css", "js", "env", "sql"]
exclude_dir = ["tmp", "vendor", ".git", "node_modules"]
delay = 1000
stop_on_error = true

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true