import { MachineRegistration } from '../types/miscTypes';

export const getRegFields = (machineRegistration?: MachineRegistration) => [
    {
        name: 'dealer_name',
        label: 'Dealer Name',
        type: 'text',
        placeholder: 'Enter dealer name',
        defaultValue: machineRegistration?.dealer_name,
    },
    {
        name: 'dealer_address',
        label: 'Dealer Address',
        type: 'text',
        placeholder: 'Enter dealer address',
        defaultValue: machineRegistration?.dealer_address,
    },
    {
        name: 'owner_name',
        label: 'Owner Name',
        type: 'text',
        placeholder: 'Enter owner name',
        defaultValue: machineRegistration?.owner_name,
    },
    {
        name: 'owner_address',
        label: 'Owner Address',
        type: 'text',
        placeholder: 'Enter owner address',
        defaultValue: machineRegistration?.owner_address,
    },
    {
        name: 'machine_model',
        label: 'Machine Model',
        type: 'text',
        placeholder: 'Enter machine model',
        defaultValue: machineRegistration?.machine_model,
    },
    {
        name: 'serial_number',
        label: 'Serial Number',
        type: 'text',
        placeholder: 'Enter serial number',
        defaultValue: machineRegistration?.serial_number,
    },
    {
        name: 'install_date',
        label: 'Installation Date',
        type: 'date',
        placeholder: 'Enter installation date',
        defaultValue: machineRegistration?.install_date,
    },
    {
        name: 'invoice_number',
        label: 'Invoice Number',
        type: 'text',
        placeholder: 'Enter invoice number',
        defaultValue: machineRegistration?.invoice_number,
    },
    {
        name: 'complete_supply',
        label: 'Complete Supply',
        type: 'select',
        placeholder: '',
        defaultValue: machineRegistration?.complete_supply ? 'true' : 'false',
        options: ['true', 'false'],
    },
    {
        name: 'pdi_complete',
        label: 'PDI Complete',
        type: 'select',
        placeholder: '',
        defaultValue: machineRegistration?.pdi_complete ? 'true' : 'false',
        options: ['true', 'false'],
    },
    {
        name: 'pto_correct',
        label: 'PTO Correct',
        type: 'select',
        placeholder: '',
        defaultValue: machineRegistration?.pto_correct ? 'true' : 'false',
        options: ['true', 'false'],
    },
    {
        name: 'machine_test_run',
        label: 'Machine Test Run',
        type: 'select',
        placeholder: '',
        defaultValue: machineRegistration?.machine_test_run ? 'true' : 'false',
        options: ['true', 'false'],
    },
    {
        name: 'safety_induction',
        label: 'Safety Induction',
        type: 'select',
        placeholder: '',
        defaultValue: machineRegistration?.safety_induction ? 'true' : 'false',
        options: ['true', 'false'],
    },
    {
        name: 'operator_handbook',
        label: 'Operator Handbook Received',
        type: 'select',
        placeholder: '',
        defaultValue: machineRegistration?.operator_handbook ? 'true' : 'false',
        options: ['true', 'false'],
    },
    {
        name: 'date',
        label: 'Date',
        type: 'date',
        placeholder: 'Enter date',
        defaultValue: machineRegistration?.date,
    },
    {
        name: 'completed_by',
        label: 'Completed By',
        type: 'text',
        placeholder: 'Enter the name of the person who completed this',
        defaultValue: machineRegistration?.completed_by,
    },
];
