# Generated by Django 6.0.2 on 2026-03-29 18:49

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Machine model name or title', max_length=255, verbose_name='name')),
                ('machine_image', models.ImageField(blank=True, help_text='Machine product image', null=True, upload_to='farmec_images/Machines/', verbose_name='image')),
                ('description', models.TextField(blank=True, help_text='Detailed machine specifications and features', null=True, verbose_name='description')),
                ('machine_link', models.URLField(blank=True, help_text='URL to machine product page', null=True, verbose_name='link')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, null=True, verbose_name='slug')),
            ],
            options={
                'db_table': 'Machine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier business name', max_length=255, verbose_name='name')),
                ('logo_image', models.ImageField(blank=True, help_text='Supplier logo', null=True, upload_to='farmec_images/Suppliers/', verbose_name='logo image')),
                ('marketing_image', models.ImageField(blank=True, help_text='Marketing/promotional image', null=True, upload_to='farmec_images/Suppliers/', verbose_name='marketing image')),
                ('description', models.TextField(blank=True, help_text='Supplier description and information', null=True, verbose_name='description')),
                ('social_facebook', models.URLField(blank=True, help_text='Facebook page URL', null=True, verbose_name='facebook')),
                ('social_twitter', models.URLField(blank=True, help_text='Twitter profile URL', null=True, verbose_name='twitter')),
                ('social_instagram', models.URLField(blank=True, help_text='Instagram profile URL', null=True, verbose_name='instagram')),
                ('social_youtube', models.URLField(blank=True, help_text='YouTube channel URL', null=True, verbose_name='youtube')),
                ('social_linkedin', models.URLField(blank=True, help_text='LinkedIn company URL', null=True, verbose_name='linkedin')),
                ('social_website', models.URLField(blank=True, help_text='Company website URL', null=True, verbose_name='website')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for this supplier', max_length=255, null=True, verbose_name='slug')),
            ],
            options={
                'db_table': 'Supplier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name or part name', max_length=255, verbose_name='name')),
                ('product_image', models.ImageField(blank=True, help_text='Product image', null=True, upload_to='farmec_images/Products/', verbose_name='image')),
                ('description', models.TextField(blank=True, help_text='Product description and details', null=True, verbose_name='description')),
                ('product_link', models.URLField(blank=True, help_text='URL to product page or datasheet', null=True, verbose_name='link')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, null=True, verbose_name='slug')),
                ('machine', models.ForeignKey(blank=True, help_text='Machine this product is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.machine', verbose_name='machine')),
            ],
            options={
                'db_table': 'Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Spareparts',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Spare part name or description', max_length=255, verbose_name='name')),
                ('parts_image', models.ImageField(blank=True, help_text='Spare part image', null=True, upload_to='farmec_images/Spareparts/', verbose_name='image')),
                ('spare_parts_link', models.URLField(blank=True, help_text='URL to spare part datasheet or ordering page', null=True, verbose_name='link')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, null=True, verbose_name='slug')),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier that provides this spare part', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'spare part',
                'verbose_name_plural': 'spare parts',
                'db_table': 'SpareParts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier that manufactures this machine', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier', verbose_name='supplier'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.URLField(blank=True, help_text='URL to video page or hosting platform', null=True, verbose_name='URL')),
                ('title', models.CharField(blank=True, help_text='Video title or name', max_length=255, null=True, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Video description and content info', null=True, verbose_name='description')),
                ('video_id', models.CharField(blank=True, help_text='Video ID from hosting platform (e.g., YouTube ID)', max_length=100, null=True, verbose_name='video ID')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to video thumbnail image', null=True, verbose_name='thumbnail')),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier associated with this video', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier', verbose_name='supplier')),
            ],
            options={
                'db_table': 'Video',
                'managed': True,
            },
        ),
    ]
