# Generated by Django 6.0.1 on 2026-01-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineitems',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LineItems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('supplier', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('machine_image', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('machine_link', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Machine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('machine', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('product_image', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_link', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spareparts',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('supplier', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('parts_image', models.TextField(blank=True, null=True)),
                ('spare_parts_link', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SpareParts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('logo_image', models.TextField(blank=True, null=True)),
                ('marketing_image', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('social_facebook', models.TextField(blank=True, null=True)),
                ('social_twitter', models.TextField(blank=True, null=True)),
                ('social_instagram', models.TextField(blank=True, null=True)),
                ('social_youtube', models.TextField(blank=True, null=True)),
                ('social_linkedin', models.TextField(blank=True, null=True)),
                ('social_website', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('supplier', models.TextField(blank=True, null=True)),
                ('web_url', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_id', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Video',
                'managed': False,
            },
        ),
    ]
