# Generated by Django 6.0.1 on 2026-01-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitems',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='spareparts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'managed': True},
        ),
    ]
