# Generated by Django 6.0.1 on 2026-01-25 22:25

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('catalog', '0002_alter_lineitems_options_alter_machine_options_and_more'), ('catalog', '0003_lineitems_created_lineitems_modified_lineitems_order_and_more'), ('catalog', '0004_alter_lineitems_id_alter_lineitems_image_and_more'), ('catalog', '0005_alter_machine_supplier_alter_product_machine_and_more')]

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitems',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='spareparts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='lineitems',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='lineitems',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='machine',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='machine',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='machine',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='video',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='video',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='video',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='lineitems',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lineitems',
            name='image',
            field=models.URLField(blank=True, help_text='URL to item image', null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='lineitems',
            name='name',
            field=models.CharField(help_text='Product or item name for line item', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lineitems',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in currency units', max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed machine specifications and features', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_image',
            field=models.URLField(blank=True, help_text='URL to machine product image', null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_link',
            field=models.URLField(blank=True, help_text='URL to machine product page', null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(help_text='Machine model name or title', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description and details', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Product name or part name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, help_text='URL to product image', null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, help_text='URL to product page or datasheet', null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='name',
            field=models.CharField(help_text='Spare part name or description', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='parts_image',
            field=models.URLField(blank=True, help_text='URL to spare part image', null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='spare_parts_link',
            field=models.URLField(blank=True, help_text='URL to spare part datasheet or ordering page', null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, help_text='Supplier description and information', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo_image',
            field=models.URLField(blank=True, help_text='URL to supplier logo', null=True, verbose_name='logo image'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='marketing_image',
            field=models.URLField(blank=True, help_text='URL to marketing/promotional image', null=True, verbose_name='marketing image'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='Supplier business name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for this supplier', max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='social_facebook',
            field=models.URLField(blank=True, help_text='Facebook page URL', null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='social_instagram',
            field=models.URLField(blank=True, help_text='Instagram profile URL', null=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='social_linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn company URL', null=True, verbose_name='linkedin'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='social_twitter',
            field=models.URLField(blank=True, help_text='Twitter profile URL', null=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='social_website',
            field=models.URLField(blank=True, help_text='Company website URL', null=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='social_youtube',
            field=models.URLField(blank=True, help_text='YouTube channel URL', null=True, verbose_name='youtube'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='Video description and content info', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL to video thumbnail image', null=True, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, help_text='Video title or name', max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, help_text='Video ID from hosting platform (e.g., YouTube ID)', max_length=100, null=True, verbose_name='video ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='web_url',
            field=models.URLField(blank=True, help_text='URL to video page or hosting platform', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier that manufactures this machine', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Machine this product is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.machine', verbose_name='machine'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier that provides this spare part', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='video',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier associated with this video', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier', verbose_name='supplier'),
        ),
    ]
