# Generated by Django 6.0.3 on 2026-04-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_normalize_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='spare_parts_link',
            field=models.URLField(blank=True, help_text='URL to spare part datasheet or ordering page', max_length=500, null=True, verbose_name='link'),
        ),
    ]
