# Generated by Django 6.0.1 on 2026-01-25 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_lineitems_id_alter_lineitems_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier that manufactures this machine', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Machine this product is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.machine', verbose_name='machine'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier that provides this spare part', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='video',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier associated with this video', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier', verbose_name='supplier'),
        ),
    ]
