# Generated by Django 6.0.4 on 2026-05-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_spareparts_spare_parts_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars). Leave blank to auto-generate.', max_length=160, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='machine',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title tag (max 70 chars). Leave blank to auto-generate.', max_length=70, null=True, verbose_name='meta title'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (max 160 chars). Leave blank to auto-generate.', max_length=160, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title tag (max 70 chars). Leave blank to auto-generate.', max_length=70, null=True, verbose_name='meta title'),
        ),
    ]
