# Generated by Django 6.0.2 on 2026-03-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_lineitems_options_alter_machine_options_and_more_squashed_0005_alter_machine_supplier_alter_product_machine_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lineitems',
        ),
    ]
