# Generated by Django 6.0.2 on 2026-03-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_drop_lineitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_image',
            field=models.ImageField(blank=True, help_text='Machine product image', null=True, upload_to='farmec_images/Machines/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, upload_to='farmec_images/Products/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='parts_image',
            field=models.ImageField(blank=True, help_text='Spare part image', null=True, upload_to='farmec_images/Spareparts/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Supplier logo', null=True, upload_to='farmec_images/Suppliers/', verbose_name='logo image'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='marketing_image',
            field=models.ImageField(blank=True, help_text='Marketing/promotional image', null=True, upload_to='farmec_images/Suppliers/', verbose_name='marketing image'),
        ),
    ]
