# Generated by Django 6.0.2 on 2026-03-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_strip_image_urls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spareparts',
            options={'managed': True, 'verbose_name': 'spare part', 'verbose_name_plural': 'spare parts'},
        ),
    ]
