# Generated by Django 6.0.1 on 2026-01-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date', models.TextField(blank=True, null=True)),
                ('main_image', models.TextField(blank=True, null=True)),
                ('subheading', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Carousel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Exhibition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Timeline',
                'managed': False,
            },
        ),
    ]
