# Generated by Django 6.0.2 on 2026-03-29 18:49

import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post headline', max_length=500, verbose_name='title')),
                ('date', models.DateField(blank=True, help_text='Publication date', null=True, verbose_name='date')),
                ('main_image', models.ImageField(blank=True, help_text='Featured/header image', null=True, upload_to='farmec_images/Blogs/', verbose_name='main image')),
                ('subheading', models.CharField(blank=True, help_text='Optional subtitle or summary', max_length=500, null=True, verbose_name='subheading')),
                ('body', models.TextField(blank=True, help_text='Blog post content', null=True, verbose_name='body')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=500, null=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'blog post',
                'verbose_name_plural': 'blog posts',
                'db_table': 'Blog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Carousel slide name or identifier', max_length=255, verbose_name='name')),
                ('image', models.ImageField(blank=True, help_text='Carousel slide image', null=True, upload_to='farmec_images/Carousels/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'carousel slide',
                'verbose_name_plural': 'carousel',
                'db_table': 'Carousel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Exhibition or event name', max_length=255, verbose_name='title')),
                ('date', models.DateField(blank=True, help_text='Event date or start date', null=True, verbose_name='date')),
                ('location', models.CharField(blank=True, help_text='Venue or location name', max_length=255, null=True, verbose_name='location')),
                ('info', models.TextField(blank=True, help_text='Event details and description', null=True, verbose_name='information')),
            ],
            options={
                'db_table': 'Exhibition',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Timeline event title', max_length=255, verbose_name='title')),
                ('date', models.DateField(blank=True, help_text='Event date', null=True, verbose_name='date')),
                ('body', models.TextField(blank=True, help_text='Event description and details', null=True, verbose_name='body')),
            ],
            options={
                'verbose_name': 'timeline event',
                'verbose_name_plural': 'timeline',
                'db_table': 'Timeline',
                'managed': True,
            },
        ),
    ]
