# Generated by Django 6.0.1 on 2026-01-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='exhibition',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'managed': True},
        ),
    ]
