# Generated by Django 6.0.1 on 2026-01-26 07:51

import django.utils.timezone
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('content', '0002_alter_blog_options_alter_carousel_options_and_more'), ('content', '0003_blog_modified_blog_order_blog_publish_blog_uid_and_more'), ('content', '0004_alter_blog_body_alter_blog_date_alter_blog_id_and_more')]

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='exhibition',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='blog',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='blog',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='blog',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modification time'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='publish'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Autogenerated unique id for this item in database', verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, help_text='Blog post content', null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, help_text='Publication date', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.URLField(blank=True, help_text='URL to featured/header image', null=True, verbose_name='main image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=500, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subheading',
            field=models.CharField(blank=True, help_text='Optional subtitle or summary', max_length=500, null=True, verbose_name='subheading'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Blog post headline', max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.URLField(blank=True, help_text='URL to carousel slide image', null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(help_text='Carousel slide name or identifier', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='date',
            field=models.DateField(blank=True, help_text='Event date or start date', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='info',
            field=models.TextField(blank=True, help_text='Event details and description', null=True, verbose_name='information'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='location',
            field=models.CharField(blank=True, help_text='Venue or location name', max_length=255, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(help_text='Exhibition or event name', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='body',
            field=models.TextField(blank=True, help_text='Event description and details', null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='date',
            field=models.DateField(blank=True, help_text='Event date', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='title',
            field=models.CharField(help_text='Timeline event title', max_length=255, verbose_name='title'),
        ),
    ]
