# Generated by Django 6.0.1 on 2026-01-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_blog_modified_blog_order_blog_publish_blog_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, help_text='Blog post content', null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, help_text='Publication date', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.URLField(blank=True, help_text='URL to featured/header image', null=True, verbose_name='main image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier', max_length=500, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subheading',
            field=models.CharField(blank=True, help_text='Optional subtitle or summary', max_length=500, null=True, verbose_name='subheading'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(help_text='Blog post headline', max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.URLField(blank=True, help_text='URL to carousel slide image', null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(help_text='Carousel slide name or identifier', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='date',
            field=models.DateField(blank=True, help_text='Event date or start date', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='info',
            field=models.TextField(blank=True, help_text='Event details and description', null=True, verbose_name='information'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='location',
            field=models.CharField(blank=True, help_text='Venue or location name', max_length=255, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(help_text='Exhibition or event name', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='body',
            field=models.TextField(blank=True, help_text='Event description and details', null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='date',
            field=models.DateField(blank=True, help_text='Event date', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='title',
            field=models.CharField(help_text='Timeline event title', max_length=255, verbose_name='title'),
        ),
    ]
