# Generated by Django 6.0.2 on 2026-03-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_blog_options_alter_carousel_options_and_more_squashed_0004_alter_blog_body_alter_blog_date_alter_blog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Featured/header image', null=True, upload_to='farmec_images/Blogs/', verbose_name='main image'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(blank=True, help_text='Carousel slide image', null=True, upload_to='farmec_images/Carousels/', verbose_name='image'),
        ),
    ]
