# Generated by Django 6.0.2 on 2026-03-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_strip_image_urls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'managed': True, 'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'managed': True, 'verbose_name': 'carousel slide', 'verbose_name_plural': 'carousel'},
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={'managed': True, 'verbose_name': 'timeline event', 'verbose_name_plural': 'timeline'},
        ),
    ]
