name: Deploy Client Application

'on':
    push:
        paths:
            - client/**

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20.9.0'

            - name: Create .env file
              run: |
                  echo "VITE_ENVIRONMENT=production" >> .env
                  echo "VITE_PUBLIC_MAPS_KEY=${{ secrets.VITE_PUBLIC_MAPS_KEY }}" >> .env
                  echo "VITE_RECAPTCHA_PUBLIC_KEY=${{ secrets.VITE_RECAPTCHA_PUBLIC_KEY }}" >> .env
                  echo "VITE_STRIPE_PUBLIC_KEY=${{ secrets.VITE_STRIPE_PUBLIC_KEY }}" >> .env
                  echo "VITE_TEST_PUBLIC_KEY=${{ secrets.VITE_TEST_PUBLIC_KEY }}" >> .env
                  echo "VITE_FB_WEB_API_KEY=${{ secrets.VITE_FB_WEB_API_KEY }}" >> .env
                  echo "VITE_FB_PROJECT_ID=${{ secrets.VITE_FB_PROJECT_ID }}" >> .env
                  echo "VITE_FB_AUTH_URL=${{ secrets.VITE_FB_AUTH_URL }}" >> .env
              working-directory: ./client

            - name: Install dependencies
              run: npm install
              working-directory: ./client

            - name: Configure AWS CLI
              run: |
                  aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

            - name: Deploy application
              run: npm run deploy
              working-directory: ./client
