name: Deploy Go Application

on:
    push:
        branches:
            - main
        paths:
            - server/**

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: '1.22'

            - name: Build Go binary
              run: |
                  cd server
                  CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o main

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: go-binary
                  path: server/main

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: go-binary

            - name: Extract binary
              run: |
                  mkdir -p extracted
                  tar -xzf main -C extracted

            - name: Copy files to EC2
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  source: extracted/main
                  target: /home/seanwelch/server/bin/main

            - name: Deploy and restart service
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      echo ${{ secrets.SUDO_PASSWORD }} | sudo -S systemctl stop farmec.service
                      echo ${{ secrets.SUDO_PASSWORD }} | sudo -S systemctl start farmec.service
                      echo ${{ secrets.SUDO_PASSWORD }} | sudo -S systemctl restart nginx
